# Generated by Django 3.1 on 2020-09-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200921_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Дата публикации'),
        ),
    ]
