# Generated by Django 3.1 on 2020-09-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='message_text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
    ]
