# Generated by Django 3.1 on 2020-11-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_auto_20200922_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='phone',
            field=models.CharField(default='author', max_length=20, verbose_name='Телефон автора'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Имя автора'),
        ),
    ]
