# Generated by Django 3.1 on 2020-09-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(max_length=300, verbose_name='Главный текст слайдера')),
                ('small_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Маленький текст слайдера')),
                ('button', models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки')),
            ],
        ),
    ]
