# Generated by Django 3.1 on 2020-09-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины покупателей'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True, 'verbose_name': 'Пользователь ', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='gramm',
            field=models.CharField(max_length=20, verbose_name='Диапазон ккал'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='answer',
            field=models.CharField(max_length=1000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('weight', 'Вес'), ('products', 'Продукты'), ('tarifs', 'Тарифы')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='',
        ),
    ]
