# Generated by Django 3.1 on 2020-09-01 13:56

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20200901_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anons_header', models.CharField(max_length=100, verbose_name='Заголовок анонса')),
                ('anons_header_bold', models.CharField(blank=True, max_length=50, null=True, verbose_name='Выделенный текст заголовка')),
                ('anons_slider_text', models.CharField(max_length=50, verbose_name='Текст слайда')),
                ('anons_slider_image', models.ImageField(upload_to=None, verbose_name='Картинка слайда')),
                ('anons_slider_bgcolor', colorfield.fields.ColorField(default='#F0F0F0', max_length=18)),
            ],
            options={
                'verbose_name': 'Анонс страницы',
                'verbose_name_plural': 'Анонс страницы',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
