# Generated by Django 3.1 on 2020-10-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_auto_20201027_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menucategory',
            name='slug',
        ),
        migrations.AddField(
            model_name='menucategory',
            name='full_slug',
            field=models.SlugField(default='pass', verbose_name='Ссылка на меню'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menucategory',
            name='short_slug',
            field=models.SlugField(default='pass', verbose_name='Ссылка на категорию'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('weight', 'Вес'), ('products', 'Продукты'), ('tarifs', 'Тарифы')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
