# Generated by Django 3.1 on 2020-09-17 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_page', '0003_auto_20200917_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'managed': True, 'verbose_name': 'Покупатель ', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='for_anonumus_user',
            new_name='for_anonymous_user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя покупателя'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('products', 'Продукты'), ('tarifs', 'Тарифы'), ('weight', 'Вес')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
