# Generated by Django 3.1 on 2020-10-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20201027_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmssmall',
            name='slug',
            field=models.SlugField(default='pass', verbose_name='Короткая ссылка категории меню'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('products', 'Продукты'), ('tarifs', 'Тарифы'), ('weight', 'Вес')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
