# Generated by Django 3.1 on 2020-09-01 13:58

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='anons_slider_bgcolor',
            field=colorfield.fields.ColorField(default='#F0F0F0', max_length=18, verbose_name='Цвет фона слайда'),
        ),
    ]
