# Generated by Django 3.1 on 2020-09-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_auto_20200910_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menulist',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AddField(
            model_name='menulist',
            name='name',
            field=models.CharField(choices=[('PROTEIN', 'Белковая диета'), ('PERFECTFITLIGHT', 'PERFECT FIT LIGHT '), ('INDIVIDUAL', 'Индивидуальное меню'), ('BALANCEDMAN', 'Сбалансированное питание мужчины'), ('HEALTHY800', 'Здоровое питание 800-1000 ккал'), ('BALANCEDWOMAN', 'Сбалансированное питание женщины'), ('OFFICEPACK', 'Офис пакет 650 ккал'), ('PERFECTFITULTRASLIM', 'PERFECT FIT ULTRA SLIM'), ('ILLFOOD', 'Питание при заболеваниях'), ('BREASTEAT', 'Грудное вскармиливание'), ('VGETERIAN', 'Вегетерианское меню'), ('HEALTHY1200', 'Здоровое питание 1200-1400 ккал'), ('PERFECTFITSTRONGMEN', 'PERFECT FIT STRONG MEN'), ('PERFECTFITSUPERSLIM', 'PERFECT FIT SUPER SLIM'), ('VIP', 'VIP - меню'), ('HEALTHY1400', 'Здоровое питание 1400-1600 ккал'), ('HEALTHY1000', 'Здоровое питание 1000-1200 ккал'), ('PERFECTFITMEDIUM', 'PERFECT FIT MEDIUM')], default='HEALTHY800', max_length=250, verbose_name='Название меню'),
        ),
    ]
