# Generated by Django 3.1 on 2020-09-01 14:58

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20200901_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anons_header', models.CharField(max_length=100, verbose_name='Заголовок анонса')),
                ('anons_header_bold', models.CharField(blank=True, max_length=50, null=True, verbose_name='Выделенный текст заголовка анонса')),
                ('calculator_header', models.CharField(max_length=100, verbose_name='Заголовок калькулятора')),
                ('menu_header', models.CharField(max_length=100, verbose_name='Заголовок меню')),
                ('menu_smalltext', models.CharField(max_length=200, verbose_name='маленький текст в меню')),
                ('buy_header', models.CharField(max_length=100, verbose_name="Заголовок 'Закажи сейчас' ")),
                ('reviews_header', models.CharField(max_length=100, verbose_name='Заголовок отзывов')),
                ('questions_header', models.CharField(max_length=100, verbose_name='Заголовок вопросов')),
            ],
            options={
                'verbose_name': 'Заголовоки страницы',
                'verbose_name_plural': 'Заголовки страницы',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PageSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anons_slider_text', models.CharField(max_length=50, verbose_name='Текст слайда')),
                ('anons_slider_image', models.ImageField(upload_to=None, verbose_name='Картинка слайда')),
                ('anons_slider_bgcolor', colorfield.fields.ColorField(default='#F0F0F0', max_length=18, verbose_name='Цвет фона слайда')),
            ],
            options={
                'verbose_name': 'Слайд анонса',
                'verbose_name_plural': 'Слайды анонса',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
