# Generated by Django 3.1 on 2020-11-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20201028_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategory',
            name='full_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Ссылка на меню'),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='short_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Ссылка на категорию'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('tarifs', 'Тарифы'), ('weight', 'Вес'), ('products', 'Продукты')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
