# Generated by Django 3.1 on 2020-09-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20200917_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='main_page.Order', verbose_name='Заказанные блюда'),
        ),
    ]
