# Generated by Django 3.1 on 2020-09-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20200910_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulist',
            name='name',
            field=models.CharField(choices=[('PERFECTFITMEDIUM', 'PERFECT FIT MEDIUM'), ('OFFICEPACK', 'Офис пакет 650 ккал'), ('PERFECTFITSTRONGMEN', 'PERFECT FIT STRONG MEN'), ('VGETERIAN', 'Вегетерианское меню'), ('PROTEIN', 'Белковая диета'), ('VIP', 'VIP - меню'), ('PERFECTFITSUPERSLIM', 'PERFECT FIT SUPER SLIM'), ('ILLFOOD', 'Питание при заболеваниях'), ('HEALTHY1200', 'Здоровое питание 1200-1400 ккал'), ('HEALTHY800', 'Здоровое питание 800-1000 ккал'), ('PERFECTFITLIGHT', 'PERFECT FIT LIGHT '), ('HEALTHY1400', 'Здоровое питание 1400-1600 ккал'), ('BREASTEAT', 'Грудное вскармиливание'), ('PERFECTFITULTRASLIM', 'PERFECT FIT ULTRA SLIM'), ('BALANCEDWOMAN', 'Сбалансированное питание женщины'), ('INDIVIDUAL', 'Индивидуальное меню'), ('HEALTHY1000', 'Здоровое питание 1000-1200 ккал'), ('BALANCEDMAN', 'Сбалансированное питание мужчины')], default='HEALTHY800', max_length=250, verbose_name='Название меню'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('weight', 'Вес'), ('products', 'Продукты'), ('tarifs', 'Тарифы')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
