# Generated by Django 3.1 on 2020-09-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20200901_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageslider',
            name='anons_slider_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название слайда'),
        ),
    ]
