# Generated by Django 3.1 on 2020-11-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_auto_20201102_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='carbohydrates',
            field=models.CharField(default='0', max_length=20, verbose_name='Колличество углеводов'),
        ),
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.CharField(default='0', max_length=20, verbose_name='Колличество жиров'),
        ),
        migrations.AddField(
            model_name='food',
            name='protein',
            field=models.CharField(default='0', max_length=20, verbose_name='Колличество белков'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('weight', 'Вес'), ('products', 'Продукты'), ('tarifs', 'Тарифы')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
