# Generated by Django 3.1 on 2020-09-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_pageslider_anons_slider_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageslider',
            name='anons_slider_link',
            field=models.CharField(max_length=50, null=True, verbose_name='Сслыка слайда'),
        ),
    ]
