# Generated by Django 3.1 on 2020-09-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_pageslider_anons_slider_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageslider',
            name='anons_slider_image',
            field=models.ImageField(upload_to='img', verbose_name='Картинка слайда'),
        ),
    ]
