# Generated by Django 3.1 on 2020-09-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_auto_20200907_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmssmall',
            name='cat',
            field=models.CharField(default='lose', max_length=50, verbose_name='Обозначение блока'),
            preserve_default=False,
        ),
    ]
