# Generated by Django 3.1 on 2020-09-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_auto_20200901_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageslider',
            name='anons_slider_link',
        ),
        migrations.RemoveField(
            model_name='pageslider',
            name='anons_slider_name',
        ),
        migrations.AlterField(
            model_name='pageslider',
            name='anons_slider_image',
            field=models.ImageField(upload_to=None, verbose_name='Картинка слайда'),
        ),
    ]
