# Generated by Django 3.1 on 2020-09-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_programmssmall_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuslider',
            options={'verbose_name': 'Блюдо ', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.RemoveField(
            model_name='menuslider',
            name='menu_list',
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('weight', 'Вес'), ('tarifs', 'Тарифы'), ('products', 'Продукты')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('OFFICEPACK', 'Офис пакет 650 ккал'), ('VGETERIAN', 'Вегетерианское меню'), ('HEALTHY800', 'Здоровое питание 800-1000 ккал'), ('PERFECTFITMEDIUM', 'PERFECT FIT MEDIUM'), ('BREASTEAT', 'Грудное вскармиливание'), ('PERFECTFITULTRASLIM', 'PERFECT FIT ULTRA SLIM'), ('ILLFOOD', 'Питание при заболеваниях'), ('HEALTHY1200', 'Здоровое питание 1200-1400 ккал'), ('PERFECTFITSTRONGMEN', 'PERFECT FIT STRONG MEN'), ('HEALTHY1400', 'Здоровое питание 1400-1600 ккал'), ('PERFECTFITLIGHT', 'PERFECT FIT LIGHT '), ('BALANCEDWOMAN', 'Сбалансированное питание женщины'), ('BALANCEDMAN', 'Сбалансированное питание мужчины'), ('PERFECTFITSUPERSLIM', 'PERFECT FIT SUPER SLIM'), ('HEALTHY1000', 'Здоровое питание 1000-1200 ккал')], default='HEALTHY800', max_length=200, verbose_name='Название меню')),
                ('menu_item', models.ManyToManyField(related_name='menu_item', to='main_page.MenuSlider', verbose_name='Позиции меню')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
