# Generated by Django 3.1 on 2020-11-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_auto_20201104_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('tarifs', 'Тарифы'), ('products', 'Продукты'), ('weight', 'Вес')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='category',
        ),
        migrations.AddField(
            model_name='reviews',
            name='category',
            field=models.ManyToManyField(to='main_page.MenuCategory', verbose_name='Меню(к которому сделан отзыв)'),
        ),
    ]
