# Generated by Django 3.1 on 2020-09-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_auto_20200901_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageslider',
            name='anons_slider_link',
            field=models.CharField(default=True, max_length=200, verbose_name='Сыылка слайда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageslider',
            name='anons_slider_name',
            field=models.CharField(default=True, max_length=50, verbose_name='Имя слайда'),
            preserve_default=False,
        ),
    ]
