# Generated by Django 3.1 on 2020-09-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_auto_20200909_2119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuGroup',
        ),
        migrations.AlterField(
            model_name='menulist',
            name='name',
            field=models.CharField(choices=[('HEALTHY1400', 'Здоровое питание 1400-1600 ккал'), ('PERFECTFITSUPERSLIM', 'PERFECT FIT SUPER SLIM'), ('OFFICEPACK', 'Офис пакет 650 ккал'), ('PERFECTFITLIGHT', 'PERFECT FIT LIGHT '), ('HEALTHY1200', 'Здоровое питание 1200-1400 ккал'), ('PERFECTFITMEDIUM', 'PERFECT FIT MEDIUM'), ('HEALTHY800', 'Здоровое питание 800-1000 ккал'), ('BALANCEDMAN', 'Сбалансированное питание мужчины'), ('PERFECTFITULTRASLIM', 'PERFECT FIT ULTRA SLIM'), ('PERFECTFITSTRONGMEN', 'PERFECT FIT STRONG MEN'), ('HEALTHY1000', 'Здоровое питание 1000-1200 ккал'), ('ILLFOOD', 'Питание при заболеваниях'), ('BREASTEAT', 'Грудное вскармиливание'), ('BALANCEDWOMAN', 'Сбалансированное питание женщины'), ('VGETERIAN', 'Вегетерианское меню')], default='HEALTHY800', max_length=200, verbose_name='Название меню'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('weight', 'Вес'), ('products', 'Продукты'), ('tarifs', 'Тарифы')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
