# Generated by Django 3.1 on 2020-09-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_auto_20200918_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='buy',
            old_name='ceated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('weight', 'Вес'), ('tarifs', 'Тарифы'), ('products', 'Продукты')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
