# Generated by Django 3.1 on 2020-09-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_auto_20200920_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmssmall',
            name='cat',
            field=models.IntegerField(verbose_name='Номер блока'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('products', 'Продукты'), ('weight', 'Вес'), ('tarifs', 'Тарифы')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
