# Generated by Django 3.1 on 2020-09-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_auto_20200920_0126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buy',
            old_name='firs_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('weight', 'Вес'), ('tarifs', 'Тарифы'), ('products', 'Продукты')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
