# Generated by Django 3.1 on 2020-09-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_auto_20200901_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammsBig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_text', models.CharField(max_length=50, verbose_name='Название блока')),
                ('big_img', models.ImageField(upload_to='img', verbose_name='Картинка блока')),
            ],
            options={
                'verbose_name': 'Большой блок ',
                'verbose_name_plural': 'Большие блоки',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProgrammsSmall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_text', models.CharField(max_length=50, verbose_name='Название блока')),
                ('small_img', models.ImageField(upload_to='img', verbose_name='Картинка блока')),
            ],
            options={
                'verbose_name': 'Маленький блок ',
                'verbose_name_plural': 'Маленькие блоки',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='pageslider',
            name='anons_slider_link',
            field=models.CharField(max_length=200, verbose_name='Сылка слайда'),
        ),
    ]
