# Generated by Django 3.1 on 2020-09-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_auto_20200901_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmsbig',
            name='big_img',
            field=models.FileField(upload_to='img', verbose_name='Картинка блока'),
        ),
        migrations.AlterField(
            model_name='programmssmall',
            name='small_img',
            field=models.FileField(upload_to='img', verbose_name='Картинка блока'),
        ),
    ]
