# Generated by Django 3.1 on 2020-09-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0014_menuslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuslider',
            name='discount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Цена со скидкой, если есть'),
        ),
        migrations.AddField(
            model_name='menuslider',
            name='price',
            field=models.CharField(default=True, max_length=10, verbose_name='Цена блюда'),
            preserve_default=False,
        ),
    ]
