# Generated by Django 3.1 on 2020-12-01 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_auto_20201202_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('weight', 'Вес'), ('tarifs', 'Тарифы'), ('products', 'Продукты')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
