# Generated by Django 3.1 on 2020-09-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_auto_20200902_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя автора')),
                ('age', models.CharField(max_length=50, verbose_name='Возраст')),
                ('text', models.CharField(max_length=50, verbose_name='Текст отзыва')),
                ('before_img', models.ImageField(upload_to='img', verbose_name='Фото "до"')),
                ('after_img', models.ImageField(upload_to='img', verbose_name='Фото "после"')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AlterModelOptions(
            name='menuslider',
            options={'verbose_name': 'Позиции меню ', 'verbose_name_plural': 'Меню'},
        ),
    ]
