# Generated by Django 3.1 on 2020-09-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0015_auto_20200920_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='status',
            field=models.CharField(choices=[('Новый заказ', 'Новый заказ'), ('Заказ в обработке', 'Заказ в обработке'), ('Заказ готов', 'Заказ готов'), ('Заказ выполнен  ', 'Заказ выполнен')], default='Новый заказ', max_length=100, verbose_name='Статус заказа'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('products', 'Продукты'), ('tarifs', 'Тарифы'), ('weight', 'Вес')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
