# Generated by Django 3.1 on 2020-09-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0016_auto_20200902_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='age',
            field=models.CharField(max_length=10, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='text',
            field=models.CharField(max_length=500, verbose_name='Текст отзыва'),
        ),
    ]
