# Generated by Django 3.1 on 2021-02-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0017_auto_20201202_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='days_name_ru',
            field=models.CharField(max_length=20, null=True, verbose_name='День недели'),
        ),
        migrations.AddField(
            model_name='days',
            name='days_name_uz',
            field=models.CharField(max_length=20, null=True, verbose_name='День недели'),
        ),
        migrations.AddField(
            model_name='food',
            name='menu_discription_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание блюда'),
        ),
        migrations.AddField(
            model_name='food',
            name='menu_discription_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Описание блюда'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название блюда'),
        ),
        migrations.AddField(
            model_name='food',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Название блюда'),
        ),
        migrations.AddField(
            model_name='headerslider',
            name='button_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='headerslider',
            name='button_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Текст кнопки'),
        ),
        migrations.AddField(
            model_name='headerslider',
            name='main_text_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Главный текст слайдера'),
        ),
        migrations.AddField(
            model_name='headerslider',
            name='main_text_uz',
            field=models.CharField(max_length=300, null=True, verbose_name='Главный текст слайдера'),
        ),
        migrations.AddField(
            model_name='headerslider',
            name='slider_header_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Обозначение о чем этот слайд'),
        ),
        migrations.AddField(
            model_name='headerslider',
            name='slider_header_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Обозначение о чем этот слайд'),
        ),
        migrations.AddField(
            model_name='headerslider',
            name='small_text_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Маленький текст слайдера'),
        ),
        migrations.AddField(
            model_name='headerslider',
            name='small_text_uz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Маленький текст слайдера'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя категории'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя категории'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='anons_header_bold_ru',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Выделенный текст заголовка анонса'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='anons_header_bold_uz',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Выделенный текст заголовка анонса'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='anons_header_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок анонса'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='anons_header_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок анонса'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='buy_header_ru',
            field=models.CharField(max_length=100, null=True, verbose_name="Заголовок 'Закажи сейчас' "),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='buy_header_uz',
            field=models.CharField(max_length=100, null=True, verbose_name="Заголовок 'Закажи сейчас' "),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='calculator_header_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок калькулятора'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='calculator_header_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок калькулятора'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='menu_header_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок меню'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='menu_header_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок меню'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='menu_smalltext_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='маленький текст в меню'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='menu_smalltext_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='маленький текст в меню'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='questions_header_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок вопросов'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='questions_header_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок вопросов'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='reviews_header_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок отзывов'),
        ),
        migrations.AddField(
            model_name='pageheaders',
            name='reviews_header_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок отзывов'),
        ),
        migrations.AddField(
            model_name='pageslider',
            name='anons_slider_name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя слайда'),
        ),
        migrations.AddField(
            model_name='pageslider',
            name='anons_slider_name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя слайда'),
        ),
        migrations.AddField(
            model_name='pageslider',
            name='anons_slider_text_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст слайда'),
        ),
        migrations.AddField(
            model_name='pageslider',
            name='anons_slider_text_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Текст слайда'),
        ),
        migrations.AddField(
            model_name='programmsbig',
            name='big_text_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название блока'),
        ),
        migrations.AddField(
            model_name='programmsbig',
            name='big_text_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Название блока'),
        ),
        migrations.AddField(
            model_name='programmssmall',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Название маленького блока'),
        ),
        migrations.AddField(
            model_name='programmssmall',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Название маленького блока'),
        ),
        migrations.AddField(
            model_name='questionsanswers',
            name='answer_ru',
            field=models.CharField(max_length=1000, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='questionsanswers',
            name='answer_uz',
            field=models.CharField(max_length=1000, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='questionsanswers',
            name='question_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='questionsanswers',
            name='question_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='age_ru',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='age_uz',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя автора'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='name_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Имя автора'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('tarifs', 'Тарифы'), ('products', 'Продукты'), ('weight', 'Вес')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
