# Generated by Django 3.1 on 2020-09-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0019_auto_20200903_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuslider',
            name='group',
            field=models.CharField(default=True, max_length=50, verbose_name='Категория блюда'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('weight', 'Вес'), ('products', 'Продукты'), ('tarifs', 'Тарифы')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
