# Generated by Django 3.1 on 2020-09-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0021_auto_20200921_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('weight', 'Вес'), ('tarifs', 'Тарифы'), ('products', 'Продукты')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
