# Generated by Django 3.1 on 2020-09-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0021_auto_20200906_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuslider',
            name='days_group',
            field=models.CharField(default=True, max_length=50, verbose_name='День недели'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuslider',
            name='group',
            field=models.CharField(choices=[('office-pack', 'Офис-пакет'), ('ill_eat', 'Питание при заболеваниях'), ('vegan_menu', 'Вегетерианское меню'), ('individual_eat', 'Индивидуальное питание'), ('for_sportsmen', 'Для спортсменов'), ('protein_diet', 'Белковая диета'), ('vip-menu', 'VIP - меню'), ('lose_weight', 'Снижение веса'), ('breast_feeding', 'Грудное вскармливание'), ('balanced_eat', 'Сбалансированная пища')], default='lose_weight', max_length=50, verbose_name='Категория блюда'),
        ),
    ]
