# Generated by Django 3.1 on 2020-09-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0022_auto_20200906_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuslider',
            name='days_group',
            field=models.CharField(choices=[('Thursday', 'Четверг'), ('Friday', 'Пятница'), ('Saturday', 'Суббота'), ('Wednesday', 'Среда'), ('Tuesday', 'Вторник'), ('Sunday', 'Воскресенье'), ('Monday', 'Понедельник')], default='Monday', max_length=50, verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='menuslider',
            name='group',
            field=models.CharField(choices=[('lose_weight', 'Снижение веса'), ('protein_diet', 'Белковая диета'), ('office-pack', 'Офис-пакет'), ('balanced_eat', 'Сбалансированная пища'), ('vip-menu', 'VIP - меню'), ('breast_feeding', 'Грудное вскармливание'), ('for_sportsmen', 'Для спортсменов'), ('ill_eat', 'Питание при заболеваниях'), ('vegan_menu', 'Вегетерианское меню'), ('individual_eat', 'Индивидуальное питание')], default='lose_weight', max_length=50, verbose_name='Категория блюда'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('tarifs', 'Тарифы'), ('products', 'Продукты'), ('weight', 'Вес')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
