# Generated by Django 3.1 on 2020-09-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0023_auto_20200922_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageslider',
            name='anons_slider_link',
            field=models.CharField(default='#', max_length=200, verbose_name='Сылка слайда'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('tarifs', 'Тарифы'), ('products', 'Продукты'), ('weight', 'Вес')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
    ]
