# Generated by Django 3.1 on 2020-09-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0023_auto_20200906_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория меню')),
            ],
            options={
                'verbose_name': 'Группа меню',
                'verbose_name_plural': 'Группы меню',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='menuslider',
            name='group',
        ),
        migrations.RemoveField(
            model_name='menuslider',
            name='days_group',
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='group',
            field=models.CharField(choices=[('tarifs', 'Тарифы'), ('weight', 'Вес'), ('products', 'Продукты')], default='products', max_length=20, verbose_name='Группа вопросов'),
        ),
        migrations.AddField(
            model_name='menuslider',
            name='menu_group',
            field=models.ManyToManyField(related_name='menu_group', to='main_page.MenuGroup', verbose_name='Категории меню'),
        ),
        migrations.AddField(
            model_name='menuslider',
            name='days_group',
            field=models.ManyToManyField(related_name='days', to='main_page.Days', verbose_name='Дни недели'),
        ),
    ]
