# Generated by Django 3.1 on 2020-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0025_auto_20200924_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='num',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер отзыва'),
        ),
    ]
